spring:
  datasource:
    url: ${DB_CONN}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (dev only, use validate/proper migrations in prod)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  security:
#    user:
#      name: admin
#      password: admin123

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    serialization:
      write-dates-as-timestamps: false
