spring:
  application:
    name: Evolve Home Sync

  profiles:
    active: dev   # default profile

  datasource:
    hikari:
      # Keep max pool size below Supabase shared pool limit (15)
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 30000 # 30 seconds
      pool-name: HikariPool-1
      validation-timeout: 5000
      leak-detection-threshold: 20000

  app:
    allowed_paths: "/api/auth/**,/api/schedule/**"
    redirect_url: ""

server:
  port: 8080
  servlet:
    context-path: /evolv
