spring:
  datasource:
    url: "${EVOLV_SPRING_DB_CONN}"
    username: "${EVOLV_SPRING_DB_USER}"
    password: "${EVOLV_SPRING_DB_PASS}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (dev only, use validate/proper migrations in prod)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    serialization:
      write-dates-as-timestamps: false

  app:
    base:
      url: "${EVOLV_SPRING_BASE_URL}"
      auth_token: "${EVOLV_SPRING_AUTH_TOKEN}"

evolv:
  jwt:
    secret: notasecret_2025_09_EvolvApp!@#1234567890
    expiration: 3600000