-- Table: public.t100_user

CREATE TABLE IF NOT EXISTS public.t100_user
(
    c100_user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c100_user_name varchar,
    c100_user_sh_name varchar,
    c100_email varchar,
    c100_hash_code varchar,
    c100_role varchar,
    c100_created_by varchar NOT NULL,
    c100_created_date timestamptz NOT NULL DEFAULT now(),
    c100_updated_date timestamp,
    c100_updated_by varchar,
    c100_void_fl varchar,
    CONSTRAINT t100_user_pkey PRIMARY KEY (c100_user_id),
    CONSTRAINT t100_user_c100_user_name_key UNIQUE (c100_user_name)
);

COMMENT ON TABLE public.t100_user IS 'User Table stores User Informations';

-- Table: public.t200_family_member

CREATE TABLE IF NOT EXISTS public.t200_family_member
(
    c200_family_member_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c200_user_id bigint NOT NULL,
    c200_name varchar,
    c200_date_of_birth date,
    c200_relationship varchar,
    c200_created_by varchar NOT NULL,
    c200_created_date timestamptz NOT NULL DEFAULT now(),
    c200_updated_date timestamp,
    c200_updated_by varchar,
    c200_void_fl varchar,
    CONSTRAINT t200_family_member_pkey PRIMARY KEY (c200_family_member_id),
    CONSTRAINT fk_t200_user FOREIGN KEY (c200_user_id)
        REFERENCES public.t100_user (c100_user_id)
);

COMMENT ON TABLE public.t200_family_member IS 'Stores family members linked to a user';

-- Table: public.t300_medication

CREATE TABLE IF NOT EXISTS public.t300_medication
(
    c300_medication_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c300_family_member_id bigint NOT NULL,
    c300_name varchar,
    c300_dosage varchar,
    c300_frequency varchar,
    c300_start_date date,
    c300_end_date date,
    c300_notes text,
    c300_created_by varchar NOT NULL,
    c300_created_date timestamptz NOT NULL DEFAULT now(),
    c300_updated_date timestamp,
    c300_updated_by varchar,
    c300_void_fl varchar,
    CONSTRAINT t300_medication_pkey PRIMARY KEY (c300_medication_id),
    CONSTRAINT fk_t300_family_member FOREIGN KEY (c300_family_member_id)
        REFERENCES public.t200_family_member (c200_family_member_id)
);

COMMENT ON TABLE public.t300_medication IS 'Stores medications for family members';

-- Table: public.t400_appointment

CREATE TABLE IF NOT EXISTS public.t400_appointment
(
    c400_appointment_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c400_family_member_id bigint NOT NULL,
    c400_type varchar,
    c400_date_time timestamptz,
    c400_notes text,
    c400_created_by varchar NOT NULL,
    c400_created_date timestamptz NOT NULL DEFAULT now(),
    c400_updated_date timestamp,
    c400_updated_by varchar,
    c400_void_fl varchar,
    CONSTRAINT t400_appointment_pkey PRIMARY KEY (c400_appointment_id),
    CONSTRAINT fk_t400_family_member FOREIGN KEY (c400_family_member_id)
        REFERENCES public.t200_family_member (c200_family_member_id)
);

COMMENT ON TABLE public.t400_appointment IS 'Stores appointments, tests, and vaccinations';

-- Table: public.t500_adherence_log

CREATE TABLE IF NOT EXISTS public.t500_adherence_log
(
    c500_adherence_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c500_medication_id bigint NOT NULL,
    c500_taken boolean NOT NULL,
    c500_timestamp timestamptz NOT NULL DEFAULT now(),
    c500_created_by varchar NOT NULL,
    c500_created_date timestamptz NOT NULL DEFAULT now(),
    c500_updated_date timestamp,
    c500_updated_by varchar,
    c500_void_fl varchar,
    CONSTRAINT t500_adherence_pkey PRIMARY KEY (c500_adherence_id),
    CONSTRAINT fk_t500_medication FOREIGN KEY (c500_medication_id)
        REFERENCES public.t300_medication (c300_medication_id)
);

COMMENT ON TABLE public.t500_adherence_log IS 'Stores adherence logs for medications';

-- Table: public.t600_prescription

CREATE TABLE IF NOT EXISTS public.t600_prescription
(
    c600_prescription_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c600_family_member_id bigint NOT NULL,
    c600_file_path varchar NOT NULL,
    c600_uploaded_at timestamptz NOT NULL DEFAULT now(),
    c600_created_by varchar NOT NULL,
    c600_created_date timestamptz NOT NULL DEFAULT now(),
    c600_updated_date timestamp,
    c600_updated_by varchar,
    c600_void_fl varchar,
    CONSTRAINT t600_prescription_pkey PRIMARY KEY (c600_prescription_id),
    CONSTRAINT fk_t600_family_member FOREIGN KEY (c600_family_member_id)
        REFERENCES public.t200_family_member (c200_family_member_id)
);

COMMENT ON TABLE public.t600_prescription IS 'Stores uploaded prescriptions for family members';


DROP TABLE public.t100_user CASCADE;
DROP TABLE public.t200_family_member CASCADE;
DROP TABLE public.t300_medication CASCADE;
DROP TABLE public.t400_appointment CASCADE;
DROP TABLE public.t500_adherence_log CASCADE;
DROP TABLE public.t600_prescription CASCADE;